### ISSUE TITLE
Create job posts templates

### ISSUE THREAD

**Issue by 42piratas** [AkashaProject/PM#11]
_From @42piratas on June 6, 2018 12:26_

- [x] Common header and footer for all openings
- [x] Smart contract developers (Blockchain engineers)
- [x] Front-end (full stack)
- [x] DevOps
- [ ] ~~Researcher blockchain~~
- [x] Community "manager" / Social media, communications

Old job postings:
https://drive.google.com/open?id=1P5GY-OIfJvCSEUjWyK4bYT9_HxFtkvmL6BOs4lzJokE
https://drive.google.com/open?id=1bmPri-kH6vwose_06oHSfJcy0L_RUIiWDyP2CGoT1vE

_Copied from original issue: AkashaProject/Community#22_

**Comment by 42piratas** [comment]
[Common header and footer for all openings](https://github.com/AkashaProject/PM/blob/master/templates/template-jobpost-header%26footer.md)

**Comment by 42piratas** [comment]
- [ ] smart contract developers (Blockchain engineers)
- [ ] front-end (full stack)
- [ ] integration, QA, devops
- [ ] researcher blockchain
- [ ] community "manager"
- [ ] social media, communications (blogposts, etc)

**Comment by 42piratas** [comment]
@kenshyx may you review and adjust the `technical requirements` for the DevOps opening, pls? Thx!
https://github.com/AkashaProject/PM/blob/master/templates/template-jobpost-devops.md

**Comment by MihaiAlisie** [comment]
The job ads can be previewed at https://hack.akasha.world/

@42piratas today @bogdanbrezuica suggested to add a field for GitHub profile (besides Linkedin). Aside from this, I think we're okay.

**Comment by MihaiAlisie** [comment]
Added the GitHub profile field and slightly changed the "Apply" form fields. Everything okay on my side :+1:

**Comment by 42piratas** [comment]
@MihaiAlisie Awesome stuff! Thanks!

We also need to POST those openings in job boards now. I will create a new issue for that.
