### ISSUE TITLE
Crowdin: allow access only to files that must be translated

### ISSUE THREAD

**Issue by 42piratas** [AkashaProject/PM#18]
Currently, translators have access to the entire tree of files inside each project, even to those files that shouldn't be translated, and that's misleading and makes the process more prone to errors.

We should block the access to files that are not supposed to be translators, so translators can only see/access the right files, and only the admins have access to all the files.

**Comment by 42piratas** [comment]
@SeverS Could you check if you have the right permissions to do that, please? And, if so, then update the permissions scheme of the files. If you don't have the permission, then I will ask help to Mihai. Thx!

**Comment by 42piratas** [comment]
@SeverS Nice that we now know that it's possible to be done.

However, I believe that you might have defined the permissions inverted. At least for the `PORTUGUESE` project, which is the one I can see as a volunteer, I can now see only the files that SHOULDN'T be translated, and I can't see the files that must be translated 😆

**Comment by SeverS** [comment]
i`ve switched the files that must be translated, so it`s ok, those are not source files anymore :)
